#
# Module manifest for module 'OTP'
#
# Generated by: Thorsten Butz
#
# Generated on: 4/30/2025
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'OTP.psm1'

    # Version number of this module.
    ModuleVersion = '0.1.0'

    # ID used to uniquely identify this module
    GUID = 'bc030be1-813d-4a7a-9f78-9eb3ed75f090'

    # Author of this module
    Author = 'Thorsten Butz'

    # Company or vendor of this module
    CompanyName = 'Produktionskrümel'

    # Copyright statement for this module
    Copyright = 'Copyright 2024 Thorsten Butz. Licensed under Apache License 2.0'

    # Description of the functionality provided by this module
    Description = 'PowerShell module for generating and managing One-Time Passwords (OTP)'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Minimum version of Microsoft .NET Framework required by this module
    DotNetFrameworkVersion = '4.7.2'

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @('lib\Otp.NET.dll', 'lib\zxing.dll')

    # Functions to export from this module
    FunctionsToExport = @('Get-OTPCode', 'New-OTPSecret', 'Read-OTPQRCode')

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport = @('gotp', 'notp', 'rotp')

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{
        Tags = @('OTP', 'TOTP', 'HOTP', '2FA', 'Authentication', 'Security', 'VibeCoding', 'EducatedPrompting', 'EduProm')
        LicenseUri = 'https://github.com/thorstenbutz/otp/blob/main/LICENSE'
        ProjectUri = 'https://github.com/thorstenbutz/otp'
        ReleaseNotes = 'Initial release of the OTP module.'
    }
}


